export enum Modifiers {
  OPEN = 'open',
  CLOSE = 'close',
  WHEEL_SPINNER_ON = 'wheel_spinner_on',
  WHEEL_SPINNER_OFF = 'wheel_spinner_off',
  EXTEND_HANDLE = 'handle_open',
  RETRACT_HANDLE = 'handle_close',
  CAMERA_BODY_DESKTOP = 'camera_body',
  CAMERA_HANDLE_DESKTOP = 'camera_handle',
  CAMERA_CORNERS_DESKTOP = 'camera_corners',
  CAMERA_WHEELS_DESKTOP = 'camera_wheels',
  CAMERA_BODY_MOBILE = 'camera_body_mobile',
  CAMERA_HANDLE_MOBILE = 'camera_handle_mobile',
  CAMERA_CORNERS_MOBILE = 'camera_corners_mobile',
  CAMERA_WHEELS_MOBILE = 'camera_wheels_mobile',
  DEFAULT_CAMERA_DESKTOP = 'default_camera_desktop',
  DEFAULT_CAMERA_MOBILE = 'default_camera_mobile',
}
